### ISSUE TITLE
Unable to use mod

### ISSUE THREAD

**Issue by TheRealIvyX** [MEEPofFaith/testing-utilities-java#11]
**Platform**: Windows

**Build**: Bleeding Edge 22624

**Mod Version**: [Latest release](https://github.com/MEEPofFaith/testing-utilities-java/releases/tag/v40) and [latest action](https://github.com/MEEPofFaith/testing-utilities-java/actions/runs/2448767808)

**Issue**: Trying to download testing utilities from the mod browser gives an error, but downloads the mod anyway
![Screenshot_4608](https://user-images.githubusercontent.com/24882599/172672685-b08837a7-3231-48ae-b4f9-467b9d10e48c.png)
However due to an error that can be seen in last_log the mod doesnt actually appear in the mods menu after downloading it and doesnt work at all. This happens on both the latest release as of writing this and the latest action as of writing this

**Steps to reproduce**: Download testing utilities and try to play mindustry with it

**Last log**: [last_log.txt](https://github.com/MEEPofFaith/testing-utilities-java/files/8863614/last_log.txt)

**Crash logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [X] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MrRoomba** [comment]
I have the same issue on android but the text is different

**Comment by MEEPofFaith** [comment]
Fixed
