### ISSUE TITLE
Unable to unisntalk the mod completely

### ISSUE THREAD

**Issue by Cordsito** [MEEPofFaith/testing-utilities-java#18]
Platform:Android

Build:23017
Mod version: The latest, I think is Minor things 2 2

Issue: When I uninstall the mod, doesn't uninstall completely and stay and that functios are usable

Steps to reproduce: Uninstall the mod

Last log: I think isn't necessary but I don't know

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ x] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**

**Comment by MEEPofFaith** [comment]
What do you mean by "doesn't uninstall completely"
You can't have half of a mod, is it or is it not removed from the mod list.

**Comment by MEEPofFaith** [comment]
Lack of information - Closing
