### ISSUE TITLE
i hate building (not ingame)

### ISSUE THREAD

**Issue by lokzz** [MEEPofFaith/testing-utilities-java#23]
**Platform**: *Android/Windows/Linux*
N/A
**Build**: *The build number under the title in the main menu. Required.*
N/A
**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*
N/A
**Issue**: *Explain your issue in detail.*
Building gives me "Could not resolve all files for configuration ':compileClasspath'"
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. clone repo
2. ./gradlew build
3. profit
**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*
N/A
**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
N/A
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [x] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by lokzz** [comment]
full crash here

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find com.github.Anuken.Arc:arc-core:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/arc-core/2b9b7c4a1d/arc-core-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/arc-core/2b9b7c4a1d/arc-core-2b9b7c4a1d.pom
     Required by:
         project :
   > Could not find com.github.Anuken.Arc:flabel:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/flabel/2b9b7c4a1d/flabel-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/flabel/2b9b7c4a1d/flabel-2b9b7c4a1d.pom
     Required by:
         project :
   > Could not find com.github.Anuken.Arc:arc-core:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/arc-core/2b9b7c4a1d/arc-core-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/arc-core/2b9b7c4a1d/arc-core-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140
   > Could not find com.github.Anuken.Arc:flabel:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/flabel/2b9b7c4a1d/flabel-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/flabel/2b9b7c4a1d/flabel-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140
   > Could not find com.github.Anuken.Arc:freetype:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/freetype/2b9b7c4a1d/freetype-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/freetype/2b9b7c4a1d/freetype-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140
   > Could not find com.github.Anuken.Arc:g3d:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/g3d/2b9b7c4a1d/g3d-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/g3d/2b9b7c4a1d/g3d-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140
   > Could not find com.github.Anuken.Arc:fx:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/fx/2b9b7c4a1d/fx-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/fx/2b9b7c4a1d/fx-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140
   > Could not find com.github.Anuken.Arc:arcnet:2b9b7c4a1d.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/Anuken/Arc/arcnet/2b9b7c4a1d/arcnet-2b9b7c4a1d.pom
       - https://www.jitpack.io/com/github/Anuken/Arc/arcnet/2b9b7c4a1d/arcnet-2b9b7c4a1d.pom
     Required by:
         project : > com.github.Anuken.Mindustry:core:v140

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

**Comment by MEEPofFaith** [comment]
Jitpack works vary strangely. I can't do anything about this nor do I know how to help.
