### ISSUE TITLE
Hide the UI ?

### ISSUE THREAD

**Issue by DaveInDev** [MEEPofFaith/testing-utilities-java#28]
Hi,
I love your tool, but I wonder if it would be possible to hide the UI during campaign ? (these red disabled buttons are disturbing for my old brain ;-) ).
Either automatically, or even manually ? (we already have F8 for console, so maybe we could have F9 for hide/show "test utilities" ?)

**Comment by MEEPofFaith** [comment]
...fair point, why do I even keep them visible anyways

**Comment by DaveInDev** [comment]
well the "kill myself" button is nice, so maybe, a simple keyboard shortcut to show/hide the UI could be nice ? :-)

**Comment by MEEPofFaith** [comment]
poof
![2023_01_22_10_34_58_Mindustry](https://user-images.githubusercontent.com/54301439/213933814-3f30a070-8423-4343-bf85-83322d26b067.png)

**Comment by DaveInDev** [comment]
I updated the mod in the mod browser, but it seems that there is no changes in my UI while in campaign : red buttons are still here. (I verified that the files in mods/meepoffaithtesting-utilities-java.zip directory have a recent date...). Did I miss something ?

**Comment by MEEPofFaith** [comment]
> I updated the mod in the mod browser, but it seems that there is no changes in my UI while in campaign : red buttons are still here. (I verified that the files in mods/meepoffaithtesting-utilities-java.zip directory have a recent date...). Did I miss something ?

The mod browser can only grab releases since TU is a java mod that needs to be compiled to be used. You can always manually download the mod from [actions](https://github.com/MEEPofFaith/testing-utilities-java/actions/runs/3981035704).

**Comment by DaveInDev** [comment]
thanks for the hint. it works like a charm !  :-)

**Comment by DaveInDev** [comment]
well yesterday I did not test it again under sandbox, and it appears that the "kill" button seems misplaced.
![image](https://user-images.githubusercontent.com/20345939/214123768-78936c75-889e-444a-8021-7bc82e789806.png)

**Comment by MEEPofFaith** [comment]
yea I fixed that already. grab from the latest action
