### ISSUE TITLE
Terrain Painter not doing anything

### ISSUE THREAD

**Issue by penguip** [MEEPofFaith/testing-utilities-java#31]
pls fix/get rid of

**Comment by MEEPofFaith** [comment]
???

https://user-images.githubusercontent.com/54301439/220507677-7e7b17f4-fe2f-4bbf-a304-b53187133155.mp4

**Comment by MEEPofFaith** [comment]
No issues, what is there to fix?

**Comment by MEEPofFaith** [comment]
Lack of info, closing.
