### ISSUE TITLE
UI Doesn't show in multiplayer

### ISSUE THREAD

**Issue by karlo292** [MEEPofFaith/testing-utilities-java#37]
**Platform**: *Android/Windows/Linux*
Windows
**Build**: *The build number under the title in the main menu. Required.*
145.1
**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*
v53
**Issue**: *Explain your issue in detail.*
Doesn't work in multiplayer, menu doesn't show. It only shows when playing maps made by me.
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Download mod from workshop
2. Join server where you have admin privileges
**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ x] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
Intentional.
It's not like they would do anything in the first place anyway after I removed the calling of `/js` due to 2r2t reasons.

**Comment by karlo292** [comment]
That's sad. I used it for testing on my server. Is there any way you could bring it back? Or add a feature if user has admin to have ability to use it.

**Comment by MEEPofFaith** [comment]
I don't know how to check if a user has admin, nor do I know how to check if a server you're playing on has a /js command in the first place.
