### ISSUE TITLE
Nothing appearing in terrain painter

### ISSUE THREAD

**Issue by Aurytis11** [MEEPofFaith/testing-utilities-java#38]
Platform: Windows

Build: 145.1

Mod Version: 53 according to mod.hjson because neither the mod browser or the description say the version.

Issue: Nothing appears in the Terrain painter window. Attached a screenshot for proof. Reload doesn't fix.

Steps to reproduce: I don't know how to reproduce the bug.
![image_2023-08-24_170536513](https://github.com/MEEPofFaith/testing-utilities-java/assets/119624161/187ded2d-9166-41ec-a602-fc8bdcb79155)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [x] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
Not the first time I've heard of this and I legitimately have no idea what the cause is.
![whyyyyyyyyyyy](https://github.com/MEEPofFaith/testing-utilities-java/assets/54301439/89fc35bc-23f5-4799-b67b-bd6767d63f23)

**Comment by Aurytis11** [comment]
just tested and it isn't because of one of my mods

**Comment by MEEPofFaith** [comment]
someone else also had this problem with no other mods installed, and then it later randomly decided to work and i have no idea why

**Comment by Aurytis11** [comment]
I was playing v5 for a bit and yesterday i booted up v7 and for some reason the terrain painter is not empty and i have no idea why.

**Comment by MEEPofFaith** [comment]
\* magic \*
