### ISSUE TITLE
crash. probably just ram issue, but I still wanna send the crash log

### ISSUE THREAD

**Issue by PikarizardCharikachu** [MEEPofFaith/testing-utilities-java#42]
**Platform**: Android

**Build**: release build 146

**Mod Version**: can't find it. all I can day is I just installed it from mindustry mod browser the same day I write this report (and also the crash)

**Issue**: what title says. I'm no coder, so I don't understand what's in the crash log xD

**Steps to reproduce**: install the mod from mod browser, restart, and crashed before the game even finished loading

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*
[last_log.txt](https://github.com/MEEPofFaith/testing-utilities-java/files/14811136/last_log.txt)

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*
[crash_1711785297806.txt](https://github.com/MEEPofFaith/testing-utilities-java/files/14811175/crash_1711785297806.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
I don't know how you're even running Mindustry with only 256mb of RAM.

**Comment by LixieWulf** [comment]
I keep seeing this comment through crash reports and it always has the same answer:
**Mindustry never can accurately get the available RAM on iOS/Android. It will always display as an extremely low value regardless of actual RAM.**

**Comment by MEEPofFaith** [comment]
Fixed now
