### ISSUE TITLE
Support for modded musics (old)

### ISSUE THREAD

**Issue by BlueTheCube** [MEEPofFaith/testing-utilities-java#43]
**I will describe the mechanics that I am proposing:**
Audio room needs to have compatibility for modded music.

Such as these [Smolkeys' Musichaos](https://github.com/SMOLKEYS/MusiChaos) and [TeamOct's Erekir Music](https://github.com/TeamOct/Erekir-Music) mods

**Comment by MEEPofFaith** [comment]
Already does? I used Team Oct's Erekir Music when testing.
Or did it break. Will check later.

**Comment by MEEPofFaith** [comment]
I see nothing wrong; I cannot reproduce your error.

![image](https://github.com/MEEPofFaith/testing-utilities-java/assets/54301439/051614b5-d1d5-4210-982c-982e2260017d)

**Comment by BlueTheCube** [comment]
Use musichaos 💀

**Comment by BlueTheCube** [comment]
and put songs in musichaos folder
