### ISSUE TITLE
MusicChaos musics not supported

### ISSUE THREAD

**Issue by BlueTheCube** [MEEPofFaith/testing-utilities-java#44]
If [Smolkeys' MusiChaos](https://github.com/SMOLKEYS/MusiChaos) mod is installed, the musics in the folder `Mindustry\musichaos` are not shown in the music room #43

**Comment by Slotterleet** [comment]
That mod does not load its own music through `Vars.tree.loadMusic()`. Are you sure musichaos itself is even working?

**Comment by BlueTheCube** [comment]
the mod is working

**Comment by BlueTheCube** [comment]
@SMOLKEYS we need to cook

**Comment by SMOLKEYS** [comment]
cant do much myself here. musichaos loads tracks from the *data directory*, not the *internal file tree*.

**Comment by SMOLKEYS** [comment]
@BlueTheCube potential workaround found, give me a bit.
