### ISSUE TITLE
bl lib bug

### ISSUE THREAD

**Issue by 123d255** [MEEPofFaith/testing-utilities-java#45]
**Platform**: *Android/Windows/Linux* windows

**Build**: *The build number under the title in the main menu. Required.* release 146 build

**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*  last

**Issue**: *Explain your issue in detail.* its requires black hole lib when bl lib installed

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.* -

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.* -

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.* not crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [x ] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
Is black hole lib enabled?
You give too little information on what the actual issue is, I can't tell what's wrong.
What does "razrab down" even mean

**Comment by 123d255** [comment]
enabled
![image](https://github.com/MEEPofFaith/testing-utilities-java/assets/116099461/345469ce-a0b8-4f39-b048-b016e09e90ab)

**Comment by 123d255** [comment]
its mean "dependecies doesnt found"

**Comment by 123d255** [comment]
enabled
![image](https://github.com/MEEPofFaith/testing-utilities-java/assets/116099461/59b9e33e-bf39-4a8f-9c04-7e2983830913)

red text mean something like "dependicies doesnt found'

**Comment by 123d255** [comment]
i think ur bl lib is broke,because its call crashes when i enable other mods which require bl lib

**Comment by SMOLKEYS** [comment]
Fun Fact:

Testing Utilities uses the Bottom Left UI library, **not** the Black Holes Library.

Link:
https://github.com/MEEPofFaith/bottom-left-ui

**Comment by MEEPofFaith** [comment]
skill issue

**Comment by 123d255** [comment]
Екарный бабай.
