### ISSUE TITLE
Game crashes upon attempt of player existence.

### ISSUE THREAD

**Issue by Mythril382** [MEEPofFaith/testing-utilities-java#47]
**Platform**: Android

**Build**: Bleeding Edge 25122

**Mod Version**: 66

**Issue**: Game crashes when the player tries to exist.

**Steps to reproduce**: Open a map, when the launch animation finishes and the player spawns or the player is already there, the game will crash.

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*

**Crash logs**: 
[crash_1720945809813.txt](https://github.com/user-attachments/files/16216140/crash_1720945809813.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
`Nulls` is removed in latest BE versions. I probably wont fix until next version because current still relies on `Nulls`.
