### ISSUE TITLE
Hitting units button causes a crash

### ISSUE THREAD

**Issue by BlueTheCube** [MEEPofFaith/testing-utilities-java#48]
**Platform**: Windows

**Build**: *bleeding-edge build 25159

**Mod Version**: 66.1 (Fix crashes in BE)

**Issue**: A crash involving that the player unit is null

**Steps to reproduce**: Hit the units button in the Testing Utilities UI

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*

**Crash logs**: 
[crash-report-08_03_2024_15_18_33.txt](https://github.com/user-attachments/files/16478482/crash-report-08_03_2024_15_18_33.txt)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
Right, Anuke reverted the removal of Nulls

**Comment by BlueTheCube** [comment]
please make a build so i can test this without crashing
