### ISSUE TITLE
UI conflict with time control

### ISSUE THREAD

**Issue by harry0805** [MEEPofFaith/testing-utilities-java#49]
**Platform**: Windows

**Build**: Steam 146

**Mod Version**: I downloaded from the in game mod menu, and I am running the current newest version of this mod.

**Issue**: The menu from this mod overlaps with the time control mod's menu.

**Steps to reproduce**: I remember the overlapping issue wasn't happening before, but this started after the switch to bottom left ui lib.

I saw the patch notes in the build that switched to bottom left ui lib, saying that it will conflict with time control, which is the reason why I wanted to make this.
Is there any chance that this will be fixed?

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [X] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
huh I didn't do this yet

**Comment by efty404** [comment]
this is happening to me as well and it is really annoying because it used to work fine

**Comment by harry0805** [comment]
> this is happening to me as well and it is really annoying because it used to work fine

For now I’m just using this version of the mod, which is the version just before the update that switches to bl-ui-lib. This will be a temporary fix until an actual patch comes out I guess.

https://github.com/MEEPofFaith/testing-utilities-java/releases/tag/v62
