### ISSUE TITLE
aaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by N0Ii** [MEEPofFaith/testing-utilities-java#5]
**Platform**: *Android//Windows/Linux*
Android
**Build**: *The build number under the title in the main menu. Required.*
The new one
**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*
V27 mod browser
**Issue**: *Explain your issue in detail.*
If i reload the game it will crash and not load to the menu
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Reload the game

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ ] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
"The new one" is not a number, and where is the crash report.

**Comment by MEEPofFaith** [comment]
No information given, closing.
