### ISSUE TITLE
crash upon opening the game

### ISSUE THREAD

**Issue by metemeto** [MEEPofFaith/testing-utilities-java#50]
when opening the game with the mod on, it crashes pnce and in the second one the game instantly closes all mods to "prevent crash loop"

**Comment by MEEPofFaith** [comment]
Thank you for giving absolutely no info.

![Telepathy](https://github.com/user-attachments/assets/cb3c9910-9824-4ee7-a828-879b7284c5fc)

**Comment by MEEPofFaith** [comment]
Wait a sec I had a template set up, you GWAAAH

**Comment by metemeto** [comment]
i have no idea what the schizophrenic hell you are talking about but okay.
crash_1731247546988.txt

Mindustry has crashed. How unfortunate.
Version: release build 146
OS: Linux xnull (aarch64)
Android API level: 33
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: none (vanilla)

> IllegalState: 'zip file closed'
ZipFile.ensureOpen: 895
ZipFile.getInputStream: 401
ZipFi.read: 2
Fi.readBytes: 1
Sound.load: 1
Sound.<init>: 5
UnitSound.lambda$init$6: 102
UnitSound$$ExternalSyntheticLambda4.run: 0
Timer$2.run: 2
AndroidGraphics.onDrawFrame: 15
GLSurfaceView$GLThread.guardedRun: 1581
GLSurfaceView$GLThread.run: 1280

i hope this is the thing you are talking about.

**Comment by MEEPofFaith** [comment]
> Mods: none (vanilla)

??????

**Comment by metemeto** [comment]
the game crashes *as soon as it loads* with the mod so thats all i got

**Comment by MEEPofFaith** [comment]
Yea I can't help you with this. The crash report says nothing about my mod so I have no idea how to fix this.

**Comment by MEEPofFaith** [comment]
Wrong button
