### ISSUE TITLE
Mod UI Lib not being read

### ISSUE THREAD

**Issue by RadioactiveRBX** [MEEPofFaith/testing-utilities-java#51]
### Platforms

Android

### Mod Version

Mindustry 14.15 (mod desc doesn't show the version)

### Issue

So I was looking for a mod to help me in finding utilities for a YouTube video. I needed to spawn an enemy so I downloaded this mod.

I already had UI Lib installed btw.

The mod continued to say "Unmet Dependicies" and saying the mod "bl_ui_lib" which I know it's the UI Lib. I reinstalled it but didn't changed, I reinstalled both UI lib and the Testing Utilities mods but nothing changed. I even tried deactivating and reactivating the UI Lib mod but still the same.

I would like help if this is about the game itself or it's something with the code reading the UI lib mod wrongly.

### Steps to reproduce

The bug happened as soon as I installed the mod and reloaded the game.

1.: Installed the mod
2.: Reloaded Mindustry
3.: UI Lib being installed and activated (I had other mods that required UI Lib
4.: Reinstalled both UI Lib and Testing Utilities mods
5.: Didn't work

That's the best way I could describe how I managed to do this.

### Submission

- [X] I have updated to the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by MEEPofFaith** [comment]
Wrong UI Lib
Use `Bottom Left UI Lib`
