### ISSUE TITLE
a minor trouble on bleeding edge

### ISSUE THREAD

**Issue by BlueTheCube** [MEEPofFaith/testing-utilities-java#52]
### Platforms

Windows

### Mod Version

68.2

### Issue

a null unit crash after entering a map

### Steps to reproduce

simply play any map, mindustry will crash

### (Crash) logs

[crash-report-12_07_2024_13_56_27.txt](https://github.com/user-attachments/files/18046433/crash-report-12_07_2024_13_56_27.txt)

### Submission

- [X] I have updated to the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by MEEPofFaith** [comment]
pain
