### ISSUE TITLE
Bring back to build 135

### ISSUE THREAD

**Issue by rylid-umil** [MEEPofFaith/testing-utilities-java#8]
**Platform**: *Windows 11*

**Build**: *135*

**Mod Version**: *Mod version in menus. If you download from actions, which action did you download from.*

**Issue**: *make a testing utilities for build 135*

**Steps to reproduce**: *testing utils is now supported for 136 and above it suck*

**Last log**: *The `last_log.txt` from your game folder (.../Mindustry). REQUIRED if a certain button is not working at ALL, usually the case in headless servers.*

**Crash logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**
  - [ ] **I am playing with the latest release (https://github.com/MEEPofFaith/testing-utilities-java/releases) to make sure my issue has not been fixed.**
   
    or
  - [ ] **I am playing with the latest action (https://github.com/MEEPofFaith/testing-utilities-java/actions) to make sure my issue has not been fixed.**

---

The original template is by Anuke, modified by sk7725, modified by MEEPofFaith.

**Comment by MEEPofFaith** [comment]
Did... did you not check the releases?
https://github.com/MEEPofFaith/testing-utilities-java/releases/tag/v37

**Comment by SMOLKEYS** [comment]
> testing utils is now supported for 136 and above it suck

mfw a mod """sucks""" because its on a newer version

@rylid-umil go cope 💀

**Comment by rylid-umil** [comment]
when i try opening the jar it doesnt open and when i installing the zip mod it says an error occoured

**Comment by MEEPofFaith** [comment]
have you tried unzipping and putting the jar in your mods folder?
